# https://symfony.com/doc/current/service_container.html
parameters:
  # ALWAYS throw exceptions for notices, warnings, etc.
  debug.error_handler.throw_at: -1

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Btmv\:
    resource: '../src'
    exclude: '../src/{Entity,Exception}'

  # vendors
  Symfony\Component\Console\Output\ConsoleOutput: ~
  Symfony\Component\Finder\Finder: ~
